CREATE TABLE settings
(
    APP_ID INTEGER NOT NULL,
    CLIENT_ID VARCHAR(256),
    SCOPE VARCHAR(128),
    REDIRECT_URI VARCHAR(256),
    RESOURCE_TYPE VARCHAR(128),
    ACCESS_TYPE VARCHAR(50),
    INCLUDE_GRANTED_SCOPES BIT,
    PRIMARY KEY(APP_ID)
);